### ISSUE TITLE
Can't import Nettle

### ISSUE THREAD

**Issue by AubinMoreau** [JuliaCrypto/Nettle.jl#105]
Hi guys, sorry to bother you but each time i try to add Nettle, i got an error : 

`(v1.2) pkg> add Nettle
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package BinDeps [9e28174c]:
 BinDeps [9e28174c] log:
 ├─possible versions are: [0.7.0, 0.8.9-0.8.10, 1.0.0-1.0.1] or uninstalled
 ├─restricted by compatibility requirements with Nettle [49dea1ee] to versions: [0.7.0, 0.8.9-0.8.10]
 │ └─Nettle [49dea1ee] log:
 │   ├─possible versions are: [0.4.0, 0.5.0] or uninstalled
 │   ├─restricted to versions * by an explicit requirement, leaving only versions [0.4.0, 0.5.0] │   └─restricted by julia compatibility requirements to versions: 0.4.0 or uninstalled, leaving only versions: 0.4.0
 └─restricted by compatibility requirements with Compat [34da2185] to versions: 1.0.0-1.0.1 or uninstalled — no versions left
   └─Compat [34da2185] log:
     ├─possible versions are: [1.0.0-1.0.1, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.5.0-1.5.1, 2.0.0, 2.1.0, 2.2.0, 3.0.0, 3.1.0, 3.2.0, 3.3.0-3.3.1, 3.4.0, 3.5.0, 3.6.0, 3.7.0, 3.8.0, 3.9.0-3.9.1, 3.10.0] or uninstalled
     └─restricted to versions 3.10.0 by an explicit requirement, leaving only versions 3.10.0 `

Even if i specifie a version, i got an error : 
`julia> Pkg.add(Pkg.PackageSpec(;name="Nettle", version="0.5.0"))
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Nettle [49dea1ee]:
 Nettle [49dea1ee] log:
 ├─possible versions are: [0.4.0, 0.5.0] or uninstalled
 ├─restricted to versions 0.5.0 by an explicit requirement, leaving only versions 0.5.0
 └─restricted by julia compatibility requirements to versions: 0.4.0 or uninstalled — no versions left`

My version of Julia : 
`julia> versioninfo()
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = "C:\Users\amoreaub\AppData\Local\atom\app-1.47.0\atom.exe"  -a
  JULIA_NUM_THREADS = 6`

Hope you can help me, and thank you in advance for your answer !

 

* ping to @staticfloat *

**Comment by staticfloat** [comment]
You have a pkg resolver conflict; this means that your package versions are incompatible.  It looks like because you are using Julia 1.2, you cannot install the latest version of `Nettle` (which is 0.5.0), and the older version of `Nettle` requires a version of `BinDeps` that conflicts with something else.

My advice is to upgrade to Julia 1.4; the newer version of `Nettle` does not require `BinDeps` at all.

**Comment by AubinMoreau** [comment]
I can't change my julia version (the project needs to be in Julia 1.2) but i will check if there is a way to avoid those conflicts, thx !
