### ISSUE TITLE
could not load symbol "nettle_hashes"

### ISSUE THREAD

**Issue by zsunberg** [JuliaCrypto/Nettle.jl#108]
When opening an issue, please ping `@staticfloat`.

With Nettle_jll 3.5, I am getting a `could not load symbol "nettle_hashes"`. See e.g. https://github.com/zsunberg/DMUStudent.jl/runs/2158159838?check_suite_focus=true#step:7:223 (have not had time to generate a minimum working example). It looks like this may have also happened in #107.

**Comment by zsunberg** [comment]
not sure if the original issue pinged you with the backquotes @staticfloat. This is to make sure.

**Comment by giordano** [comment]
Fixed by #109?

**Comment by zsunberg** [comment]
Yep, it appears to be fixed!
