### ISSUE TITLE
Pushing for v1.0

### ISSUE THREAD

**Issue by nandoconde** [JuliaCrypto/Nettle.jl#111]
Hello

I see the repo has been stable for a year and the number of stars is not too bad. Is there anything holding back a v1.0 release?

It would display a very good image of the maturity and stability of the cryptography ecosystem in Julia.

@staticfloat

**Comment by staticfloat** [comment]
I think one thing that would be useful first is to solve #110.  My understanding is that it should be fairly simple, we just need to check that `all(data[end-padlen:end] .== data[end])`, and if not, we should raise an error.  Also, we would need tests for it.

**Comment by nandoconde** [comment]
Well, now that the small issues have been closed, what would be the roadmap?
Maybe updating the binaries to the latest Nettle?

@staticfloat

**Comment by staticfloat** [comment]
Since we're pretty convinced that the current Nettle binaries are stable, let's just keep with these and update later when someone actually needs a new feature.  :)
