### ISSUE TITLE
Remove AbstractString names for Ciphers?

### ISSUE THREAD

**Issue by nandoconde** [JuliaCrypto/Nettle.jl#113]
Revising the code I noticed that names are saved as `AbstractString`. Not that it matters much performance-wise, since everything is done in the C-callee, but maybe it is unnecessary, and they could be plain old regular `String`.

Plus, maybe it makes sense to have them be `Symbol` because it is more idiomatic, but I do not feel very strong about this.

@staticfloat

**Comment by staticfloat** [comment]
Agreed, it should be a `String`, not an `AbstractString`.
